import type { Metadata } from "next";
import { FileText } from "lucide-react";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { OrganizationPicker } from "@/components/organizations/organization-picker";
import { getOrganizations } from "@/data/organizations";
import App from "@/components/App";
import "./globals.css";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarHead } from "@/components/sidebar-head";
import { SiteHeader } from "@/components/site-header";

import { cookies } from "next/headers";
import { PRIVACY_MODE_COOKIE } from "@/lib/privacy-mode";
import { PrivacyModeProvider } from "@/components/providers/privacy-mode-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const organizations = await getOrganizations();
  const cookieStore = await cookies();
  const privacyModeEnabled =
    cookieStore.get(PRIVACY_MODE_COOKIE)?.value === "true";

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background`}
      >
        <App>
          <PrivacyModeProvider initialEnabled={privacyModeEnabled}>
            <div className="[--header-height:calc(--spacing(14))]">
              <SidebarProvider className="flex flex-col">
                <SiteHeader />
                <div className="flex flex-1">
                  <AppSidebar organizations={organizations} />
                  <SidebarInset>{children}</SidebarInset>
                </div>
              </SidebarProvider>
            </div>
            <Toaster />
          </PrivacyModeProvider>
        </App>
      </body>
    </html>
  );
}
