export const FISCAL_VALIDATION_RULES = {
  INVOICE: {
    CANNOT_GENERATE_INCOME: "INV-01",
    CANCELLED_NO_ALLOCATIONS: "INV-02",
    ALLOCATION_LIMIT: "INV-03",
    PAYMENT_STATUS_DERIVED: "INV-04",
  },
  PAYMENT: {
    POSITIVE_AMOUNT: "PAY-01",
    NO_FUTURE_DATE: "PAY-02",
    ALLOCATION_SUM_LIMIT: "PAY-03",
  },
  ALLOCATION: {
    POSITIVE_AMOUNT: "ALL-01",
    INVOICE_NOT_CANCELLED: "ALL-02",
    INVOICE_SUM_LIMIT: "ALL-03",
    PAYMENT_SUM_LIMIT: "ALL-04",
    MATCH_FISCAL_PERIOD: "ALL-05",
    IMMUTABLE: "ALL-06",
  },
} as const;

export type FiscalValidationRuleCode =
  | (typeof FISCAL_VALIDATION_RULES.INVOICE)[keyof typeof FISCAL_VALIDATION_RULES.INVOICE]
  | (typeof FISCAL_VALIDATION_RULES.PAYMENT)[keyof typeof FISCAL_VALIDATION_RULES.PAYMENT]
  | (typeof FISCAL_VALIDATION_RULES.ALLOCATION)[keyof typeof FISCAL_VALIDATION_RULES.ALLOCATION];
