export const FISCAL_VALIDATION_RULES = {
  INTEGRITY: {
    INVOICE_CANNOT_GENERATE_INCOME: "INT-INV-01",
    INVOICE_CANCELLED_NO_ALLOCATIONS: "INT-INV-02",
    INVOICE_ALLOCATION_LIMIT: "INT-INV-03",
    INVOICE_PAYMENT_STATUS_DERIVED: "INT-INV-04",
    INVOICE_NON_RESICO_REGIME: "INT-INV-05",
    PAYMENT_POSITIVE_AMOUNT: "INT-PAY-01",
    PAYMENT_NO_FUTURE_DATE: "INT-PAY-02",
    PAYMENT_ALLOCATION_SUM_LIMIT: "INT-PAY-03",
    ALLOCATION_POSITIVE_AMOUNT: "INT-ALL-01",
    ALLOCATION_INVOICE_NOT_CANCELLED: "INT-ALL-02",
    ALLOCATION_INVOICE_SUM_LIMIT: "INT-ALL-03",
    ALLOCATION_PAYMENT_SUM_LIMIT: "INT-ALL-04",
    ALLOCATION_MATCH_FISCAL_PERIOD: "INT-ALL-05",
    ALLOCATION_IMMUTABLE: "INT-ALL-06",
    ALLOCATION_DATE_MISMATCH: "INT-ALL-07",
    INVOICE_SUBTOTAL_INCONSISTENCY: "INT-INV-06",
    INVOICE_MISSING_ITEM_TAXES: "INT-INV-07",
  },
  USER_FACING: {
    INVOICE_MISSING_ISR_WITHHOLDING: "USR-INV-01",
    INVOICE_INVALID_EXCHANGE_RATE: "USR-INV-02",
  },
} as const;

export type FiscalValidationRuleCode =
  | (typeof FISCAL_VALIDATION_RULES.INTEGRITY)[keyof typeof FISCAL_VALIDATION_RULES.INTEGRITY]
  | (typeof FISCAL_VALIDATION_RULES.USER_FACING)[keyof typeof FISCAL_VALIDATION_RULES.USER_FACING];
